version: "3.9"
networks:
  inside:
    driver: bridge
  traefik-net:
    external: true

services:
  markert-generation-backend:
    container_name: markert-generation-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app
    networks:
      - inside
      - traefik-net 
    ports:
      - "8075:5000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      FLASK_DEBUG: 1
    labels:
      - "traefik.enable=true"
      - "traefik.port=8088" # port of the traefik instance
      - "traefik.docker.network=traefik-net" # traefik network
      - "traefik.http.routers.markert-generation-be.rule=PathPrefix(`/markert-generation-backend`)" # URL path to your backend, replace YOUR-BACKEND with an unique string to name your router
      - "traefik.http.middlewares.strip-markert-generation-be.stripprefix.prefixes=/markert-generation-backend" # declare strip prefix middleware from above, replace strip-YOUR-PATH with an unique name
      - "traefik.http.routers.markert-generation-be.middlewares=strip-markert-generation-be@docker" # add middleware that strips of your path, replace YOUR-BACKEND with the router name above, replace strip-YOUR-PATH with the middleware's name above

  # builds the frontend
  markert-generation-frontend:
    container_name: markert-generation-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - inside
    volumes:
      - ./frontend/build/:/ui/build/
      - ./frontend/public:/ui/public
      - ./frontend/src/:/ui/src/
    environment: 
      - PUBLIC_URL=http://btn6xd.inf.uni-bayreuth.de/markert-generation-frontend/
      - BACKEND_URL=http://btn6xd.inf.uni-bayreuth.de/markert-generation-backend/

  # serves the frontend
  markert-generation-nginx:
    container_name: markert-generation-nginx
    image: nginx
    ports:
      - 8876:80
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/frontend/public
    depends_on:
      - markert-generation-backend
    networks:
      - inside
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.port=8088" # port of the traefik instance
      - "traefik.docker.network=traefik-net" # traefik network
      - "traefik.http.routers.markert-generation-fe.rule=PathPrefix(`/markert-generation-frontend`)" # URL path to your backend, replace YOUR-BACKEND with an unique string to name your router
      - "traefik.http.middlewares.strip-markert-generation-fe.stripprefix.prefixes=/markert-generation-frontend" # declare strip prefix middleware from above, replace strip-YOUR-PATH with an unique name
      - "traefik.http.routers.markert-generation-fe.middlewares=strip-markert-generation-fe@docker" # add middleware that strips of your path, replace YOUR-BACKEND with the router name above, replace strip>
 
